### PR TITLE
Kakute board updates

### PR DESCRIPTION
**Pull request by HThuren**
Documentation for KakuteH7 and KakuteH7v2

### CODE REVIEW

**Comment by HThuren** [comment]
Hi @haslinghuis, are this the right way of updating wiki ?

**Review by haslinghuis — APPROVED** [review]

**Comment by HThuren** [comment]
Gosh, many identical kakute files

**Comment by HThuren** [comment]
@haslinghuis , not sure, but I think I need a merge to see the change at wiki

**Comment by HThuren** [comment]
Thank you

**Comment by HThuren** [comment]
hi @haslinghuis and @blckmn , I got this merged but not end up in https://github.com/betaflight/betaflight/wiki
can you help what are missing ?
(also if I are going to update the wiki link where a board file exist)

**Comment by haslinghuis** [comment]
Looking at the wiki itself the menu is not updated:

```
 - [KAKUTE F3](KAKUTE-F3)
 - [KAKUTEF4](Board---KAKUTEF4)
 - [KAKUTEF4V2](Board---KAKUTEF4V2)
 - [KAKUTEF7](Board---KAKUTEF7)
 ```
 
 Doing manual now to see if changes come up.

**Comment by HThuren** [comment]
> Looking at the wiki itself the menu is not updated:
> 
> ```
>  - [KAKUTE F3](KAKUTE-F3)
>  - [KAKUTEF4](Board---KAKUTEF4)
>  - [KAKUTEF4V2](Board---KAKUTEF4V2)
>  - [KAKUTEF7](Board---KAKUTEF7)
> ```
> 
> Doing manual now to see if changes come up.

The _sidebar are updated, but the above borad--- are missing or the link I made in _sidebar are wrong.

**Comment by haslinghuis** [comment]
We might need some sort of indexer here if content and menu entries are pushed by PR.

**Comment by haslinghuis** [comment]
@HThuren we are working on a new documentation platform. Please consider joining Discord.

**Comment by HThuren** [comment]
@haslinghuis , I'm on discord, # documentation tab ?

**Pull request merged**
